USE veterinariapegadas;

CREATE TABLE pessoa(
-- UNSIGNED NÃO PERMITE IDS EM NUMERO NEGATIVOS
idPessoa INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(60) NOT NULL,
cpf VARCHAR(11) NOT NULL UNIQUE,
telefone VARCHAR(20) NOT NULL UNIQUE,
email VARCHAR(50) NOT NULL
);

CREATE TABLE animal (
idAnimal INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
idPessoa INT(6) UNSIGNED,
nome VARCHAR(60) NOT NULL,
especie VARCHAR(60) NOT NULL,
raca VARCHAR(60) NOT NULL
);

CREATE TABLE atendimento (
idAtendimento INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
idPessoa INT(6) UNSIGNED,
idAnimal INT(6) UNSIGNED,
atendente VARCHAR(60) NOT NULL,
descricao TEXT NOT NULL
);